# Generated by Django 3.1.13 on 2022-02-08 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_shell', '0007_auto_20210413_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='status_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='executionresult',
            name='status_modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executionresult',
            name='status',
            field=models.CharField(choices=[], default='created', max_length=50),
        ),
    ]
